### ISSUE TITLE
Turns on when saving a file

### ISSUE THREAD

**Issue by timonson** [RRethy/vim-hexokinase#32]
Hi,  
you fixed my last issue https://github.com/RRethy/vim-hexokinase/issues/30 mostly. The only issue now is that when hexokinase is turned off and you save a file, it toggles to being 'turned on' and shows the colors. It happens in **vim**.

Thank you!

**Comment by RRethy** [comment]
That should fix it, thanks for letting me know.

**Comment by timonson** [comment]
When turned off and saving a file I still get this error: `E315: ml_get: invalid lnum: 39` and it enables **hexokinase**.
